micronaut:
  application:
    name: ${project.artifactId}

  server:
    port: 8080
    forward-headers:
      protocol-header: X-Forwarded-Proto
      port-header: X-Forwarded-Port
      host-header: X-Forwarded-Host
      prefix-header: X-Forwarded-Prefix

  metrics:
    enabled: true
    export:
      prometheus:
        step: PT2s
        descriptions: false

---

datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: password
    dialect: MYSQL

# Postgres connection example
#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/db
#    driverClassName: org.postgresql.Driver
#    username: user
#    password: pwd
#    dialect: POSTGRES

jpa:
  default:
    packages-to-scan:
      - 'org.fiware.iam.repository'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
      locations:  classpath:db/migration/common,classpath:db/migration/mysql
      # H2 migration
      # locations:  classpath:db/migration/common,classpath:db/migration/mysql
      # Postgresql migration
      # locations:  classpath:db/migration/postgresql